services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    env_file:
      - ./CoursePlatform/.env

  web:
    image:  rakeshkarki/web:latest
    ports: 
      - "8080:8000"
    env_file:
      - ./CoursePlatform/.env
    
    depends_on:
      - db