

name : Django CI

on:
  push:
    branches:
      - main

jobs:
    test:
       runs-on: ubuntu-latest
       
       services:
          postgres :
             image : postgres:17
             env   :
                POSTGRES_DB: test_db
                POSTGRES_USER: postgres
                POSTGRES_PASSWOR: postgres
       
       env  :
          POSTGRES_USER : postgres
          POSTGRES_DB : test_db
          POSTGRES_PASSWORD : postgres
          POSTGRES_HOST : localhost
          POSTGRES_PORT : 5432

       steps:
          - name : Checkout Repository
            uses : actions/checkout@v4

          - name : Setup Python
            uses : actions/setup-python@v5
            with : 
               python-version: "3.13"

          - name : Install requirements
            run  : pip install -r ./CoursePlatform/requirements.txt

          - name : Run Check 
            run  :  |
                cd CoursePlatform
                python manage.py check 

          - name : Run test
            run  :  |
                cd CoursePlatform
                python manage.py test 

    build:
      needs: test
      runs-on: ubuntu-latest
      
      env:
        DOCKER_USERNAME : ${{ vars.DOCKER_USERNAME }}
       
      steps:
         - name : Checkout Repository
           uses : actions/checkout@v4

         - name : Login to DockerHub
           uses : docker/login-action@v3
           with : 
              username : ${{ env.DOCKER_USERNAME }}
              password : ${{ secrets.DOCKER_TOKEN }}

        
         - name : Build app 
           run  : |
              docker build \
              -t $DOCKER_USERNAME/web:${{ github.sha }} \
              -t $DOCKER_USERNAME/web:latest \
              ./CoursePlatform

         - name : Push app
           run  : |
              docker push $DOCKER_USERNAME/web:${{ github.sha }}
              docker push $DOCKER_USERNAME/web:latest 


    deploy:
      needs: build

      runs-on: self-hosted

      steps:
      - name : Deploy
        run  : |
            cd /home/rakesh/Desktop/practices/django/sass-app/

            docker compose down --remove-orphans || true 
            docker compose pull 
            docker compose up -d

         
        
